### ISSUE TITLE
Does not work in the modpack

### ISSUE THREAD

**Issue by Paradox75831004** [JazzyLucas/CalculateScrapForQuota#1]
Does not work in the build of mods. What could be the problem?

Assembly code - 018d39d9-ef0b-8184-8200- 54c45264e21c

![image](https://github.com/JazzyLucas/CalculateScrapForQuota/assets/72872478/c171e4ef-c46b-4acc-b033-f91aac3d3446)

**Comment by EleventhLucas** [comment]
scrap needs to be in the ship, but I'll look into including scrap outside the ship when at the company

**Comment by Paradox75831004** [comment]
> scrap needs to be in the ship, but I'll look into including scrap outside the ship when at the company

It is also not outlined in green on the ship

**Comment by NilaierMusic** [comment]
Yeah, the mod doesn't seem to work at all. I've tried every version from 1.0.0 to 1.0.2
No error in the console, but the mod does get loaded into the game. It seems that there might be some sort of code logic oversight that either prevents HUD and Highlighting from showing up or the mod doesn't count the amount of objects at all, which, in turn, doesn't trigger other parts of the code.

**Comment by EleventhLucas** [comment]
published [1.0.3](https://thunderstore.io/c/lethal-company/p/Jazzy/CalculateScrapForQuota/versions/) let me know if it works out

**Comment by Paradox75831004** [comment]
It kind of worked out, but for some reason, after lifting and dropping, it incorrectly highlights in green. After re-entering the save, it does not allocate at all.

018d3ebd-21ec-23c8-9ef4-7d095a8278fa

**Comment by Paradox75831004** [comment]
> published [1.0.3](https://thunderstore.io/c/lethal-company/p/Jazzy/CalculateScrapForQuota/versions/) let me know if it works out

It kind of worked out, but for some reason, after lifting and dropping, it incorrectly highlights in green. After re-entering the save, it does not allocate at all.

018d3ebd-21ec-23c8-9ef4-7d095a8278fa

Everything works, but sometimes something goes wrong and it shows the wrong way. Maybe this is an isolated case, I'll write a bug report later. For now, we will test the build with streamers and other players to gather more information

**Comment by Paradox75831004** [comment]
![image](https://github.com/JazzyLucas/CalculateScrapForQuota/assets/72872478/320129a3-c935-42b3-9247-43cb5012da67)
After handing over the quota of necessary items, until the monster took the goods, I started scanning the remaining loot. The scan failed - after which I couldn't use it at all

If I fly into orbit, everything falls into place and I can scan again

**Comment by EleventhLucas** [comment]
I appreciate the info and patience. 1.0.5 should fix it
