### ISSUE TITLE
Buying up a company - out of sync - below 100% of the cost

### ISSUE THREAD

**Issue by Paradox75831004** [JazzyLucas/CalculateScrapForQuota#4]
If you fly to a company where the sale of scrap metal is below 100% of the purchase, then the calculation is not correct, it is based on the real price, and not the one at which the company buys

The assembly code for the test is 018d5822-a06f-24ac-5124-2aaf16b11400

![image](https://github.com/JazzyLucas/CalculateScrapForQuota/assets/72872478/7723e06a-6dc2-4128-8f67-bc3ce09583eb)

**Comment by EleventhLucas** [comment]
1.1.0 should account for buying rate (you need to be highlighting scrap at the company building)
